### ISSUE TITLE
Inventory agent on O.S MI

### ISSUE THREAD

**Issue by albertomna** [flyve-mdm/android-inventory-agent#247]
Hello guys, 
Thank you a lot for this project, it work perfectly!!!
I have only one problem with OS MI (like Smartphone Xiaomi).
The App crash at the start and the error text is the following:
"android.app.RemoteServiceException: Bad notification posted from package org.flyve.inventory.agent: Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=org.flyve.inventory.agent id=0x7f0d0000) visible user=0 )
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:176)
at android.app.ActivityThread.main(ActivityThread.java:6635)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)"

**Comment by stonebuzz** [comment]
Hi @albertomna ,

can you test with latest commit on develop branch ?

Best regards
